// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package base

import (
	"database/sql"
	"time"
)

type Certificate struct {
	ID                 int64          `json:"id"`
	SerialNumber       string         `json:"serial_number"`
	CommonName         string         `json:"common_name"`
	Type               string         `json:"type"`
	KeyID              int64          `json:"key_id"`
	IssuerSerialNumber sql.NullString `json:"issuer_serial_number"`
	NotBefore          time.Time      `json:"not_before"`
	NotAfter           time.Time      `json:"not_after"`
	Skid               string         `json:"skid"`
	Akid               string         `json:"akid"`
	IsRevoked          sql.NullInt64  `json:"is_revoked"`
	RevocationReason   sql.NullInt64  `json:"revocation_reason"`
	RevocationTime     sql.NullTime   `json:"revocation_time"`
	CertificatePem     string         `json:"certificate_pem"`
	Status             string         `json:"status"`
	CreatedAt          sql.NullTime   `json:"created_at"`
}

type Crl struct {
	ID         int64        `json:"id"`
	Name       string       `json:"name"`
	CrlNumber  int64        `json:"crl_number"`
	IssuerID   int64        `json:"issuer_id"`
	ThisUpdate time.Time    `json:"this_update"`
	NextUpdate time.Time    `json:"next_update"`
	CrlPem     string       `json:"crl_pem"`
	CreatedAt  sql.NullTime `json:"created_at"`
}

type Csr struct {
	ID            int64         `json:"id"`
	CommonName    string        `json:"common_name"`
	KeyID         int64         `json:"key_id"`
	Status        string        `json:"status"`
	CsrPem        string        `json:"csr_pem"`
	CertificateID sql.NullInt64 `json:"certificate_id"`
	CreatedAt     sql.NullTime  `json:"created_at"`
}

type Key struct {
	ID            int64        `json:"id"`
	Name          string       `json:"name"`
	Algorithm     string       `json:"algorithm"`
	PrivateKeyPem string       `json:"private_key_pem"`
	PublicKeyPem  string       `json:"public_key_pem"`
	CreatedAt     sql.NullTime `json:"created_at"`
}
