// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package base

import (
	"context"
	"database/sql"
	"time"
)

const createCRL = `-- name: CreateCRL :one
INSERT INTO crls (
    name,
    crl_number,
    issuer_id,
    this_update,
    next_update,
    crl_pem
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5,
    ?6
)
RETURNING id, name, crl_number, issuer_id, this_update, next_update, crl_pem, created_at
`

type CreateCRLParams struct {
	Name       string    `json:"name"`
	CrlNumber  int64     `json:"crl_number"`
	IssuerID   int64     `json:"issuer_id"`
	ThisUpdate time.Time `json:"this_update"`
	NextUpdate time.Time `json:"next_update"`
	CrlPem     string    `json:"crl_pem"`
}

func (q *Queries) CreateCRL(ctx context.Context, arg CreateCRLParams) (Crl, error) {
	row := q.db.QueryRowContext(ctx, createCRL,
		arg.Name,
		arg.CrlNumber,
		arg.IssuerID,
		arg.ThisUpdate,
		arg.NextUpdate,
		arg.CrlPem,
	)
	var i Crl
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CrlNumber,
		&i.IssuerID,
		&i.ThisUpdate,
		&i.NextUpdate,
		&i.CrlPem,
		&i.CreatedAt,
	)
	return i, err
}

const createCSR = `-- name: CreateCSR :one
INSERT INTO csrs (
    common_name,
    key_id,
    status,
    csr_pem,
    certificate_id
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5
)
RETURNING id, common_name, key_id, status, csr_pem, certificate_id, created_at
`

type CreateCSRParams struct {
	CommonName    string        `json:"common_name"`
	KeyID         int64         `json:"key_id"`
	Status        string        `json:"status"`
	CsrPem        string        `json:"csr_pem"`
	CertificateID sql.NullInt64 `json:"certificate_id"`
}

func (q *Queries) CreateCSR(ctx context.Context, arg CreateCSRParams) (Csr, error) {
	row := q.db.QueryRowContext(ctx, createCSR,
		arg.CommonName,
		arg.KeyID,
		arg.Status,
		arg.CsrPem,
		arg.CertificateID,
	)
	var i Csr
	err := row.Scan(
		&i.ID,
		&i.CommonName,
		&i.KeyID,
		&i.Status,
		&i.CsrPem,
		&i.CertificateID,
		&i.CreatedAt,
	)
	return i, err
}

const createCertificate = `-- name: CreateCertificate :one
INSERT INTO certificates (
    serial_number,
    common_name,
    type,
    key_id,
    issuer_serial_number,
    skid,
    akid,
    status,
    not_before,
    not_after,
    certificate_pem
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5,
    ?6,
    ?7,
    ?8,
    ?9,
    ?10,
    ?11
)
RETURNING id, serial_number, common_name, type, key_id, issuer_serial_number, not_before, not_after, skid, akid, is_revoked, revocation_reason, revocation_time, certificate_pem, status, created_at
`

type CreateCertificateParams struct {
	SerialNumber       string         `json:"serial_number"`
	CommonName         string         `json:"common_name"`
	Type               string         `json:"type"`
	KeyID              int64          `json:"key_id"`
	IssuerSerialNumber sql.NullString `json:"issuer_serial_number"`
	Skid               string         `json:"skid"`
	Akid               string         `json:"akid"`
	Status             string         `json:"status"`
	NotBefore          time.Time      `json:"not_before"`
	NotAfter           time.Time      `json:"not_after"`
	CertificatePem     string         `json:"certificate_pem"`
}

func (q *Queries) CreateCertificate(ctx context.Context, arg CreateCertificateParams) (Certificate, error) {
	row := q.db.QueryRowContext(ctx, createCertificate,
		arg.SerialNumber,
		arg.CommonName,
		arg.Type,
		arg.KeyID,
		arg.IssuerSerialNumber,
		arg.Skid,
		arg.Akid,
		arg.Status,
		arg.NotBefore,
		arg.NotAfter,
		arg.CertificatePem,
	)
	var i Certificate
	err := row.Scan(
		&i.ID,
		&i.SerialNumber,
		&i.CommonName,
		&i.Type,
		&i.KeyID,
		&i.IssuerSerialNumber,
		&i.NotBefore,
		&i.NotAfter,
		&i.Skid,
		&i.Akid,
		&i.IsRevoked,
		&i.RevocationReason,
		&i.RevocationTime,
		&i.CertificatePem,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const createKeyPair = `-- name: CreateKeyPair :one
INSERT INTO keys (
    name,
    algorithm,
    private_key_pem,
    public_key_pem
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4
)
RETURNING id, name, algorithm, private_key_pem, public_key_pem, created_at
`

type CreateKeyPairParams struct {
	Name          string `json:"name"`
	Algorithm     string `json:"algorithm"`
	PrivateKeyPem string `json:"private_key_pem"`
	PublicKeyPem  string `json:"public_key_pem"`
}

func (q *Queries) CreateKeyPair(ctx context.Context, arg CreateKeyPairParams) (Key, error) {
	row := q.db.QueryRowContext(ctx, createKeyPair,
		arg.Name,
		arg.Algorithm,
		arg.PrivateKeyPem,
		arg.PublicKeyPem,
	)
	var i Key
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Algorithm,
		&i.PrivateKeyPem,
		&i.PublicKeyPem,
		&i.CreatedAt,
	)
	return i, err
}

const getCRLByID = `-- name: GetCRLByID :one
SELECT id, name, crl_number, issuer_id, this_update, next_update, crl_pem, created_at FROM crls WHERE id = ?1
`

func (q *Queries) GetCRLByID(ctx context.Context, id int64) (Crl, error) {
	row := q.db.QueryRowContext(ctx, getCRLByID, id)
	var i Crl
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CrlNumber,
		&i.IssuerID,
		&i.ThisUpdate,
		&i.NextUpdate,
		&i.CrlPem,
		&i.CreatedAt,
	)
	return i, err
}

const getCSRByID = `-- name: GetCSRByID :one
SELECT id, common_name, key_id, status, csr_pem, certificate_id, created_at FROM csrs WHERE id = ?1
`

func (q *Queries) GetCSRByID(ctx context.Context, id int64) (Csr, error) {
	row := q.db.QueryRowContext(ctx, getCSRByID, id)
	var i Csr
	err := row.Scan(
		&i.ID,
		&i.CommonName,
		&i.KeyID,
		&i.Status,
		&i.CsrPem,
		&i.CertificateID,
		&i.CreatedAt,
	)
	return i, err
}

const getCertificateByCN = `-- name: GetCertificateByCN :one
SELECT id, serial_number, common_name, type, key_id, issuer_serial_number, not_before, not_after, skid, akid, is_revoked, revocation_reason, revocation_time, certificate_pem, status, created_at FROM certificates WHERE common_name = ?1
`

func (q *Queries) GetCertificateByCN(ctx context.Context, commonName string) (Certificate, error) {
	row := q.db.QueryRowContext(ctx, getCertificateByCN, commonName)
	var i Certificate
	err := row.Scan(
		&i.ID,
		&i.SerialNumber,
		&i.CommonName,
		&i.Type,
		&i.KeyID,
		&i.IssuerSerialNumber,
		&i.NotBefore,
		&i.NotAfter,
		&i.Skid,
		&i.Akid,
		&i.IsRevoked,
		&i.RevocationReason,
		&i.RevocationTime,
		&i.CertificatePem,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getCertificateByID = `-- name: GetCertificateByID :one
SELECT id, serial_number, common_name, type, key_id, issuer_serial_number, not_before, not_after, skid, akid, is_revoked, revocation_reason, revocation_time, certificate_pem, status, created_at FROM certificates WHERE id = ?1
`

func (q *Queries) GetCertificateByID(ctx context.Context, id int64) (Certificate, error) {
	row := q.db.QueryRowContext(ctx, getCertificateByID, id)
	var i Certificate
	err := row.Scan(
		&i.ID,
		&i.SerialNumber,
		&i.CommonName,
		&i.Type,
		&i.KeyID,
		&i.IssuerSerialNumber,
		&i.NotBefore,
		&i.NotAfter,
		&i.Skid,
		&i.Akid,
		&i.IsRevoked,
		&i.RevocationReason,
		&i.RevocationTime,
		&i.CertificatePem,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getCertificateBySKID = `-- name: GetCertificateBySKID :one
SELECT id, serial_number, common_name, type, key_id, issuer_serial_number, not_before, not_after, skid, akid, is_revoked, revocation_reason, revocation_time, certificate_pem, status, created_at FROM certificates WHERE skid = ?1
`

func (q *Queries) GetCertificateBySKID(ctx context.Context, skid string) (Certificate, error) {
	row := q.db.QueryRowContext(ctx, getCertificateBySKID, skid)
	var i Certificate
	err := row.Scan(
		&i.ID,
		&i.SerialNumber,
		&i.CommonName,
		&i.Type,
		&i.KeyID,
		&i.IssuerSerialNumber,
		&i.NotBefore,
		&i.NotAfter,
		&i.Skid,
		&i.Akid,
		&i.IsRevoked,
		&i.RevocationReason,
		&i.RevocationTime,
		&i.CertificatePem,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getCertificateBySN = `-- name: GetCertificateBySN :one
SELECT id, serial_number, common_name, type, key_id, issuer_serial_number, not_before, not_after, skid, akid, is_revoked, revocation_reason, revocation_time, certificate_pem, status, created_at FROM certificates WHERE serial_number = ?1
`

func (q *Queries) GetCertificateBySN(ctx context.Context, serialNumber string) (Certificate, error) {
	row := q.db.QueryRowContext(ctx, getCertificateBySN, serialNumber)
	var i Certificate
	err := row.Scan(
		&i.ID,
		&i.SerialNumber,
		&i.CommonName,
		&i.Type,
		&i.KeyID,
		&i.IssuerSerialNumber,
		&i.NotBefore,
		&i.NotAfter,
		&i.Skid,
		&i.Akid,
		&i.IsRevoked,
		&i.RevocationReason,
		&i.RevocationTime,
		&i.CertificatePem,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getCertificateSerialNumberByID = `-- name: GetCertificateSerialNumberByID :one
SELECT serial_number FROM certificates WHERE id = ?1
`

func (q *Queries) GetCertificateSerialNumberByID(ctx context.Context, id int64) (string, error) {
	row := q.db.QueryRowContext(ctx, getCertificateSerialNumberByID, id)
	var serial_number string
	err := row.Scan(&serial_number)
	return serial_number, err
}

const getKeyByID = `-- name: GetKeyByID :one
SELECT id, name, algorithm, private_key_pem, public_key_pem, created_at FROM keys WHERE id = ?1
`

func (q *Queries) GetKeyByID(ctx context.Context, id int64) (Key, error) {
	row := q.db.QueryRowContext(ctx, getKeyByID, id)
	var i Key
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Algorithm,
		&i.PrivateKeyPem,
		&i.PublicKeyPem,
		&i.CreatedAt,
	)
	return i, err
}

const getKeyByName = `-- name: GetKeyByName :one
SELECT id, name, algorithm, private_key_pem, public_key_pem, created_at FROM keys WHERE name = ?1
`

func (q *Queries) GetKeyByName(ctx context.Context, name string) (Key, error) {
	row := q.db.QueryRowContext(ctx, getKeyByName, name)
	var i Key
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Algorithm,
		&i.PrivateKeyPem,
		&i.PublicKeyPem,
		&i.CreatedAt,
	)
	return i, err
}

const getLatestCRL = `-- name: GetLatestCRL :one
SELECT
    name,
    crl_number,
    issuer_id,
    this_update,
    next_update,
    crl_pem
FROM crls
WHERE issuer_id = ?1
ORDER BY created_at DESC
LIMIT 1
`

type GetLatestCRLRow struct {
	Name       string    `json:"name"`
	CrlNumber  int64     `json:"crl_number"`
	IssuerID   int64     `json:"issuer_id"`
	ThisUpdate time.Time `json:"this_update"`
	NextUpdate time.Time `json:"next_update"`
	CrlPem     string    `json:"crl_pem"`
}

func (q *Queries) GetLatestCRL(ctx context.Context, issuerID int64) (GetLatestCRLRow, error) {
	row := q.db.QueryRowContext(ctx, getLatestCRL, issuerID)
	var i GetLatestCRLRow
	err := row.Scan(
		&i.Name,
		&i.CrlNumber,
		&i.IssuerID,
		&i.ThisUpdate,
		&i.NextUpdate,
		&i.CrlPem,
	)
	return i, err
}

const listAllCRLs = `-- name: ListAllCRLs :many
SELECT id, name, crl_number, issuer_id, this_update, next_update, crl_pem, created_at FROM crls
WHERE issuer_id = ?1
ORDER BY id ASC
`

func (q *Queries) ListAllCRLs(ctx context.Context, issuerID int64) ([]Crl, error) {
	rows, err := q.db.QueryContext(ctx, listAllCRLs, issuerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Crl
	for rows.Next() {
		var i Crl
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CrlNumber,
			&i.IssuerID,
			&i.ThisUpdate,
			&i.NextUpdate,
			&i.CrlPem,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllCSRs = `-- name: ListAllCSRs :many
SELECT id, common_name, key_id, status, csr_pem, certificate_id
FROM csrs
WHERE (CAST(?1 AS TEXT) IS NULL OR status = CAST(?1 AS TEXT))
ORDER BY id ASC
`

type ListAllCSRsRow struct {
	ID            int64         `json:"id"`
	CommonName    string        `json:"common_name"`
	KeyID         int64         `json:"key_id"`
	Status        string        `json:"status"`
	CsrPem        string        `json:"csr_pem"`
	CertificateID sql.NullInt64 `json:"certificate_id"`
}

func (q *Queries) ListAllCSRs(ctx context.Context, status sql.NullString) ([]ListAllCSRsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllCSRs, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllCSRsRow
	for rows.Next() {
		var i ListAllCSRsRow
		if err := rows.Scan(
			&i.ID,
			&i.CommonName,
			&i.KeyID,
			&i.Status,
			&i.CsrPem,
			&i.CertificateID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllCertificates = `-- name: ListAllCertificates :many
SELECT id, serial_number, common_name, type, status, not_after, is_revoked
FROM certificates
WHERE
    (CAST(?1 AS TEXT) IS NULL OR status = CAST(?1 AS TEXT))
    AND (CAST(?2 AS TEXT) IS NULL OR type = CAST(?2 AS TEXT))
ORDER BY id ASC
`

type ListAllCertificatesParams struct {
	Status sql.NullString `json:"status"`
	Type   sql.NullString `json:"type"`
}

type ListAllCertificatesRow struct {
	ID           int64         `json:"id"`
	SerialNumber string        `json:"serial_number"`
	CommonName   string        `json:"common_name"`
	Type         string        `json:"type"`
	Status       string        `json:"status"`
	NotAfter     time.Time     `json:"not_after"`
	IsRevoked    sql.NullInt64 `json:"is_revoked"`
}

func (q *Queries) ListAllCertificates(ctx context.Context, arg ListAllCertificatesParams) ([]ListAllCertificatesRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllCertificates, arg.Status, arg.Type)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllCertificatesRow
	for rows.Next() {
		var i ListAllCertificatesRow
		if err := rows.Scan(
			&i.ID,
			&i.SerialNumber,
			&i.CommonName,
			&i.Type,
			&i.Status,
			&i.NotAfter,
			&i.IsRevoked,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllKeys = `-- name: ListAllKeys :many
SELECT id, name, algorithm, created_at
FROM keys
ORDER BY id ASC
`

type ListAllKeysRow struct {
	ID        int64        `json:"id"`
	Name      string       `json:"name"`
	Algorithm string       `json:"algorithm"`
	CreatedAt sql.NullTime `json:"created_at"`
}

func (q *Queries) ListAllKeys(ctx context.Context) ([]ListAllKeysRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllKeysRow
	for rows.Next() {
		var i ListAllKeysRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Algorithm,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllRevokedCertificates = `-- name: ListAllRevokedCertificates :many
SELECT id, serial_number, common_name, type, key_id, issuer_serial_number, not_before, not_after, skid, akid, is_revoked, revocation_reason, revocation_time, certificate_pem, status, created_at FROM certificates
WHERE
    issuer_serial_number = ?1
    AND is_revoked = 1
ORDER BY id ASC
`

func (q *Queries) ListAllRevokedCertificates(ctx context.Context, issuerSerialNumber sql.NullString) ([]Certificate, error) {
	rows, err := q.db.QueryContext(ctx, listAllRevokedCertificates, issuerSerialNumber)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Certificate
	for rows.Next() {
		var i Certificate
		if err := rows.Scan(
			&i.ID,
			&i.SerialNumber,
			&i.CommonName,
			&i.Type,
			&i.KeyID,
			&i.IssuerSerialNumber,
			&i.NotBefore,
			&i.NotAfter,
			&i.Skid,
			&i.Akid,
			&i.IsRevoked,
			&i.RevocationReason,
			&i.RevocationTime,
			&i.CertificatePem,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCRLs = `-- name: ListCRLs :many
SELECT id, name, crl_number, issuer_id, this_update, next_update, crl_pem, created_at FROM crls
WHERE issuer_id = ?1
ORDER BY id ASC
LIMIT ?3
OFFSET ?2
`

type ListCRLsParams struct {
	IssuerID int64 `json:"issuer_id"`
	Offset   int64 `json:"offset"`
	Limit    int64 `json:"limit"`
}

func (q *Queries) ListCRLs(ctx context.Context, arg ListCRLsParams) ([]Crl, error) {
	rows, err := q.db.QueryContext(ctx, listCRLs, arg.IssuerID, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Crl
	for rows.Next() {
		var i Crl
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CrlNumber,
			&i.IssuerID,
			&i.ThisUpdate,
			&i.NextUpdate,
			&i.CrlPem,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCSRs = `-- name: ListCSRs :many
SELECT id, common_name, key_id, status, csr_pem, certificate_id
FROM csrs
WHERE (CAST(?1 AS TEXT) IS NULL OR status = CAST(?1 AS TEXT))
ORDER BY id ASC
LIMIT ?3
OFFSET ?2
`

type ListCSRsParams struct {
	Status sql.NullString `json:"status"`
	Offset int64          `json:"offset"`
	Limit  int64          `json:"limit"`
}

type ListCSRsRow struct {
	ID            int64         `json:"id"`
	CommonName    string        `json:"common_name"`
	KeyID         int64         `json:"key_id"`
	Status        string        `json:"status"`
	CsrPem        string        `json:"csr_pem"`
	CertificateID sql.NullInt64 `json:"certificate_id"`
}

func (q *Queries) ListCSRs(ctx context.Context, arg ListCSRsParams) ([]ListCSRsRow, error) {
	rows, err := q.db.QueryContext(ctx, listCSRs, arg.Status, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCSRsRow
	for rows.Next() {
		var i ListCSRsRow
		if err := rows.Scan(
			&i.ID,
			&i.CommonName,
			&i.KeyID,
			&i.Status,
			&i.CsrPem,
			&i.CertificateID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCertificates = `-- name: ListCertificates :many
SELECT id, serial_number, common_name, type, status, not_after, is_revoked
FROM certificates
WHERE
    (CAST(?1 AS TEXT) IS NULL OR status = CAST(?1 AS TEXT))
    AND (CAST(?2 AS TEXT) IS NULL OR type = CAST(?2 AS TEXT))
ORDER BY id ASC
LIMIT ?4
OFFSET ?3
`

type ListCertificatesParams struct {
	Status sql.NullString `json:"status"`
	Type   sql.NullString `json:"type"`
	Offset int64          `json:"offset"`
	Limit  int64          `json:"limit"`
}

type ListCertificatesRow struct {
	ID           int64         `json:"id"`
	SerialNumber string        `json:"serial_number"`
	CommonName   string        `json:"common_name"`
	Type         string        `json:"type"`
	Status       string        `json:"status"`
	NotAfter     time.Time     `json:"not_after"`
	IsRevoked    sql.NullInt64 `json:"is_revoked"`
}

func (q *Queries) ListCertificates(ctx context.Context, arg ListCertificatesParams) ([]ListCertificatesRow, error) {
	rows, err := q.db.QueryContext(ctx, listCertificates,
		arg.Status,
		arg.Type,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCertificatesRow
	for rows.Next() {
		var i ListCertificatesRow
		if err := rows.Scan(
			&i.ID,
			&i.SerialNumber,
			&i.CommonName,
			&i.Type,
			&i.Status,
			&i.NotAfter,
			&i.IsRevoked,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listKeys = `-- name: ListKeys :many
SELECT id, name, algorithm, created_at
FROM keys
ORDER BY id ASC
LIMIT ?2
OFFSET ?1
`

type ListKeysParams struct {
	Offset int64 `json:"offset"`
	Limit  int64 `json:"limit"`
}

type ListKeysRow struct {
	ID        int64        `json:"id"`
	Name      string       `json:"name"`
	Algorithm string       `json:"algorithm"`
	CreatedAt sql.NullTime `json:"created_at"`
}

func (q *Queries) ListKeys(ctx context.Context, arg ListKeysParams) ([]ListKeysRow, error) {
	rows, err := q.db.QueryContext(ctx, listKeys, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListKeysRow
	for rows.Next() {
		var i ListKeysRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Algorithm,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRevokedCertificates = `-- name: ListRevokedCertificates :many
SELECT id, serial_number, common_name, type, key_id, issuer_serial_number, not_before, not_after, skid, akid, is_revoked, revocation_reason, revocation_time, certificate_pem, status, created_at FROM certificates
WHERE
    issuer_serial_number = ?1
    AND is_revoked = 1
ORDER BY id ASC
LIMIT ?3
OFFSET ?2
`

type ListRevokedCertificatesParams struct {
	IssuerSerialNumber sql.NullString `json:"issuer_serial_number"`
	Offset             int64          `json:"offset"`
	Limit              int64          `json:"limit"`
}

func (q *Queries) ListRevokedCertificates(ctx context.Context, arg ListRevokedCertificatesParams) ([]Certificate, error) {
	rows, err := q.db.QueryContext(ctx, listRevokedCertificates, arg.IssuerSerialNumber, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Certificate
	for rows.Next() {
		var i Certificate
		if err := rows.Scan(
			&i.ID,
			&i.SerialNumber,
			&i.CommonName,
			&i.Type,
			&i.KeyID,
			&i.IssuerSerialNumber,
			&i.NotBefore,
			&i.NotAfter,
			&i.Skid,
			&i.Akid,
			&i.IsRevoked,
			&i.RevocationReason,
			&i.RevocationTime,
			&i.CertificatePem,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeCertificate = `-- name: RevokeCertificate :one
UPDATE certificates
SET
    is_revoked = COALESCE(?1, is_revoked),
    revocation_reason = COALESCE(?2, revocation_reason),
    revocation_time = COALESCE(?3, revocation_time),
    status = COALESCE(?4, status)
WHERE serial_number = ?5
RETURNING id, serial_number, common_name, type, key_id, issuer_serial_number, not_before, not_after, skid, akid, is_revoked, revocation_reason, revocation_time, certificate_pem, status, created_at
`

type RevokeCertificateParams struct {
	IsRevoked        sql.NullInt64 `json:"is_revoked"`
	RevocationReason sql.NullInt64 `json:"revocation_reason"`
	RevocationTime   sql.NullTime  `json:"revocation_time"`
	Status           string        `json:"status"`
	SerialNumber     string        `json:"serial_number"`
}

func (q *Queries) RevokeCertificate(ctx context.Context, arg RevokeCertificateParams) (Certificate, error) {
	row := q.db.QueryRowContext(ctx, revokeCertificate,
		arg.IsRevoked,
		arg.RevocationReason,
		arg.RevocationTime,
		arg.Status,
		arg.SerialNumber,
	)
	var i Certificate
	err := row.Scan(
		&i.ID,
		&i.SerialNumber,
		&i.CommonName,
		&i.Type,
		&i.KeyID,
		&i.IssuerSerialNumber,
		&i.NotBefore,
		&i.NotAfter,
		&i.Skid,
		&i.Akid,
		&i.IsRevoked,
		&i.RevocationReason,
		&i.RevocationTime,
		&i.CertificatePem,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const updateCSRStatus = `-- name: UpdateCSRStatus :exec
UPDATE csrs
SET status = ?1, certificate_id = ?2
WHERE common_name = ?3
`

type UpdateCSRStatusParams struct {
	Status        string        `json:"status"`
	CertificateID sql.NullInt64 `json:"certificate_id"`
	CommonName    string        `json:"common_name"`
}

func (q *Queries) UpdateCSRStatus(ctx context.Context, arg UpdateCSRStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateCSRStatus, arg.Status, arg.CertificateID, arg.CommonName)
	return err
}

const updateCertificate = `-- name: UpdateCertificate :one
UPDATE certificates
SET
  common_name = COALESCE(?1, common_name),
  type = COALESCE(?2, type),
  key_id = COALESCE(?3, key_id),
  issuer_serial_number = COALESCE(?4, issuer_serial_number),
  skid = COALESCE(?5, skid),
  akid = COALESCE(?6, akid),
  status = COALESCE(?7, status),
  not_before = COALESCE(?8, not_before),
  not_after = COALESCE(?9, not_after),
  certificate_pem = COALESCE(?10, certificate_pem)
WHERE serial_number = ?11
RETURNING id, serial_number, common_name, type, key_id, issuer_serial_number, not_before, not_after, skid, akid, is_revoked, revocation_reason, revocation_time, certificate_pem, status, created_at
`

type UpdateCertificateParams struct {
	CommonName         sql.NullString `json:"common_name"`
	Type               sql.NullString `json:"type"`
	KeyID              sql.NullInt64  `json:"key_id"`
	IssuerSerialNumber sql.NullString `json:"issuer_serial_number"`
	Skid               sql.NullString `json:"skid"`
	Akid               sql.NullString `json:"akid"`
	Status             sql.NullString `json:"status"`
	NotBefore          sql.NullTime   `json:"not_before"`
	NotAfter           sql.NullTime   `json:"not_after"`
	CertificatePem     sql.NullString `json:"certificate_pem"`
	SerialNumber       string         `json:"serial_number"`
}

func (q *Queries) UpdateCertificate(ctx context.Context, arg UpdateCertificateParams) (Certificate, error) {
	row := q.db.QueryRowContext(ctx, updateCertificate,
		arg.CommonName,
		arg.Type,
		arg.KeyID,
		arg.IssuerSerialNumber,
		arg.Skid,
		arg.Akid,
		arg.Status,
		arg.NotBefore,
		arg.NotAfter,
		arg.CertificatePem,
		arg.SerialNumber,
	)
	var i Certificate
	err := row.Scan(
		&i.ID,
		&i.SerialNumber,
		&i.CommonName,
		&i.Type,
		&i.KeyID,
		&i.IssuerSerialNumber,
		&i.NotBefore,
		&i.NotAfter,
		&i.Skid,
		&i.Akid,
		&i.IsRevoked,
		&i.RevocationReason,
		&i.RevocationTime,
		&i.CertificatePem,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}
