// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package base

import (
	"context"
	"database/sql"
)

type Querier interface {
	CreateCRL(ctx context.Context, arg CreateCRLParams) (Crl, error)
	CreateCSR(ctx context.Context, arg CreateCSRParams) (Csr, error)
	CreateCertificate(ctx context.Context, arg CreateCertificateParams) (Certificate, error)
	CreateKeyPair(ctx context.Context, arg CreateKeyPairParams) (Key, error)
	GetCRLByID(ctx context.Context, id int64) (Crl, error)
	GetCSRByID(ctx context.Context, id int64) (Csr, error)
	GetCertificateByCN(ctx context.Context, commonName string) (Certificate, error)
	GetCertificateByID(ctx context.Context, id int64) (Certificate, error)
	GetCertificateBySKID(ctx context.Context, skid string) (Certificate, error)
	GetCertificateBySN(ctx context.Context, serialNumber string) (Certificate, error)
	GetCertificateSerialNumberByID(ctx context.Context, id int64) (string, error)
	GetKeyByID(ctx context.Context, id int64) (Key, error)
	GetKeyByName(ctx context.Context, name string) (Key, error)
	GetLatestCRL(ctx context.Context, issuerID int64) (GetLatestCRLRow, error)
	ListAllCRLs(ctx context.Context, issuerID int64) ([]Crl, error)
	ListAllCSRs(ctx context.Context, status sql.NullString) ([]ListAllCSRsRow, error)
	ListAllCertificates(ctx context.Context, arg ListAllCertificatesParams) ([]ListAllCertificatesRow, error)
	ListAllKeys(ctx context.Context) ([]ListAllKeysRow, error)
	ListAllRevokedCertificates(ctx context.Context, issuerSerialNumber sql.NullString) ([]Certificate, error)
	ListCRLs(ctx context.Context, arg ListCRLsParams) ([]Crl, error)
	ListCSRs(ctx context.Context, arg ListCSRsParams) ([]ListCSRsRow, error)
	ListCertificates(ctx context.Context, arg ListCertificatesParams) ([]ListCertificatesRow, error)
	ListKeys(ctx context.Context, arg ListKeysParams) ([]ListKeysRow, error)
	ListRevokedCertificates(ctx context.Context, arg ListRevokedCertificatesParams) ([]Certificate, error)
	RevokeCertificate(ctx context.Context, arg RevokeCertificateParams) (Certificate, error)
	UpdateCSRStatus(ctx context.Context, arg UpdateCSRStatusParams) error
	UpdateCertificate(ctx context.Context, arg UpdateCertificateParams) (Certificate, error)
}

var _ Querier = (*Queries)(nil)
