// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql"
	"time"
)

type Certificate struct {
	ID           string
	KeyID        string
	SerialNumber string
	CertType     string
	Subject      string
	Issuer       string
	NotBefore    time.Time
	NotAfter     time.Time
	PemContent   string
	CreatedAt    sql.NullTime
}

type Key struct {
	ID         string
	KeyType    string
	PublicKey  string
	PrivateKey []byte
	CreatedAt  sql.NullTime
}
