// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlc

import (
	"context"
	"time"
)

const createCertificate = `-- name: CreateCertificate :one
INSERT INTO certificates (id, key_id, serial_number, cert_type, subject, issuer, not_before, not_after, pem_content)
VALUES (?1, ?2, ?3, ?4, ?5,
		?6, ?7, ?8, ?9)
RETURNING id, key_id, serial_number, cert_type, subject, issuer, not_before, not_after, pem_content, created_at
`

type CreateCertificateParams struct {
	ID           string
	KeyID        string
	SerialNumber string
	CertType     string
	Subject      string
	Issuer       string
	NotBefore    time.Time
	NotAfter     time.Time
	PemContent   string
}

func (q *Queries) CreateCertificate(ctx context.Context, arg CreateCertificateParams) (Certificate, error) {
	row := q.db.QueryRowContext(ctx, createCertificate,
		arg.ID,
		arg.KeyID,
		arg.SerialNumber,
		arg.CertType,
		arg.Subject,
		arg.Issuer,
		arg.NotBefore,
		arg.NotAfter,
		arg.PemContent,
	)
	var i Certificate
	err := row.Scan(
		&i.ID,
		&i.KeyID,
		&i.SerialNumber,
		&i.CertType,
		&i.Subject,
		&i.Issuer,
		&i.NotBefore,
		&i.NotAfter,
		&i.PemContent,
		&i.CreatedAt,
	)
	return i, err
}

const createKey = `-- name: CreateKey :one
INSERT INTO keys (id, key_type, public_key, private_key)
VALUES (?1, ?2, ?3, ?4)
RETURNING id, key_type, public_key, private_key, created_at
`

type CreateKeyParams struct {
	ID         string
	KeyType    string
	PublicKey  string
	PrivateKey []byte
}

func (q *Queries) CreateKey(ctx context.Context, arg CreateKeyParams) (Key, error) {
	row := q.db.QueryRowContext(ctx, createKey,
		arg.ID,
		arg.KeyType,
		arg.PublicKey,
		arg.PrivateKey,
	)
	var i Key
	err := row.Scan(
		&i.ID,
		&i.KeyType,
		&i.PublicKey,
		&i.PrivateKey,
		&i.CreatedAt,
	)
	return i, err
}

const listCertificates = `-- name: ListCertificates :many
SELECT id, key_id, serial_number, cert_type, subject, issuer, not_before, not_after, pem_content, created_at
FROM certificates
ORDER BY created_at DESC
`

func (q *Queries) ListCertificates(ctx context.Context) ([]Certificate, error) {
	rows, err := q.db.QueryContext(ctx, listCertificates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Certificate
	for rows.Next() {
		var i Certificate
		if err := rows.Scan(
			&i.ID,
			&i.KeyID,
			&i.SerialNumber,
			&i.CertType,
			&i.Subject,
			&i.Issuer,
			&i.NotBefore,
			&i.NotAfter,
			&i.PemContent,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listKeys = `-- name: ListKeys :many
SELECT id, key_type, public_key, private_key, created_at
FROM keys
ORDER BY created_at DESC
`

func (q *Queries) ListKeys(ctx context.Context) ([]Key, error) {
	rows, err := q.db.QueryContext(ctx, listKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Key
	for rows.Next() {
		var i Key
		if err := rows.Scan(
			&i.ID,
			&i.KeyType,
			&i.PublicKey,
			&i.PrivateKey,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
